### ISSUE TITLE
Gogoanime Get Streaming Links 404

### ISSUE THREAD

**Issue by izulwahidin** [consumet/api.consumet.org#533] opened 2023-11-25 06:00 UTC
### Describe the bug

Gogoanime return status code 404 on all query to get Streaming Links

### Steps to reproduce

`curl https://w-consumet-api.vercel.app/anime/gogoanime/watch/spy-x-family-episode-1`
or
`curl https://api.consumet.org//anime/gogoanime/watch/spy-x-family-episode-1`

### Expected behavior

`{
  "headers": {
      "Referer": "string",
      "watchsb": "string", // or null, since only provided with server being equal to "streamsb".
      "User-Agent": "string" // or null
  },
  "sources": [
      {
      "url": "string",
      "quality": "string",
      "isM3U8": true
      }
  ]
}`

### Actual behavior

`"message": {}`

**Comment by carlosesteven** [comment] 2023-11-25 07:12
@izulwahidin The cause of that problem is that today gogoanime changed its main domain to: https://anitaku.to.

You can solve this problem by changing the domain here: https://github.com/carlosesteven/consumet.ts/blob/master/src/providers/anime/gogoanime.ts#L23

My copy of the repository: https://github.com/carlosesteven/api.consumet.org/

Test: https://api-consumet-3lqsgk5t7-carlosesteven.vercel.app/anime/gogoanime/watch/spy-x-family-episode-1

**Comment by LUMINARSFT** [comment] 2023-11-25 10:25
@carlosesteven Hello sir i have faced the same problem. I followed below steps as you menstioned in previous reply.

Step 1 : I forked both https://github.com/carlosesteven/api.consumet.org and Consumet.ts repos into my github. 

Step2 : Then i changed the line you mentioned to https://anitaku.to. 

Step3 : Then i fully redeploy my application. 

But still streaming links are not working. Is my steps correct or should i change anything else. Thank you for your great contribution.

**Comment by shibotto** [comment] 2023-11-25 15:05
It is fairly hit and miss for now. At the moment it's working for me, but I've been greeted all day by a cloudflare broken host message on anitaku.to/home.

**Comment by riimuru** [comment] 2023-11-25 16:19
@izulwahidin This issue has been fixed as of https://github.com/consumet/consumet.ts/commit/41242b46c7c7a8a1eb12bcbe551001c784313e0a. Make sure that you're self-hosting the API & update the dependencies on [api.consumet.org](https://github.com/riimuru) to stay up to date with the consumet.ts code. Thank you for your report!

**Closed by riimuru** 2023-11-25 16:19 UTC
Labels: bug
